### ISSUE TITLE
Manage permLevel

### ISSUE THREAD

**Issue by ghost** [M4GNV5/Hack.ChatBot#24]
Hi , what "users.json" do exactly ?
how can I manage permLevel of users ?

Tnx

**Comment by M4GNV5** [comment]
`users.json` is a map of trip code -> permission level, so e.g. my trip code is cronuS i have the permission level 42. Actually setting that to higher than 5 is useless but meh ^^. You can see what commands need what permission level in [Permissions.md](https://github.com/M4GNV5/Hack.ChatBot/blob/master/Permissions.md) and you can change what command needs what permission level in [requiredPerm.json](https://github.com/M4GNV5/Hack.ChatBot/blob/master/src/data/requiredPerm.json)

**Comment by ghost** [comment]
yes I know that but it's not work !
"BD74uK": 2 , this trip code defined to "ToastyStoemp" user and perm level : 2
I logged in by ToastyStoemp#BD74uK and entered "/ascii" : 
@ToastyStoemp you dont have the permission to use this command

**Comment by M4GNV5** [comment]
You login using username#password that password will be hashed and the first 6 characters will be your trip code, ergo you need to think of a good password, look what trip code you have and put that into the `users.json` you cannot use our trip codes (as our passwords are secret)

**Comment by ghost** [comment]
so I can't set manually trip code for users and put into `users.json` ?
where should I set my passwords ?

**Comment by M4GNV5** [comment]
You dont set the passwords anywhere, just connect to hack.chat with your password and it will give you a trip code. Thats what you put into users.json, thats all.

**Comment by ToastyStoemp** [comment]
Plz no steal account 😕

**Comment by M4GNV5** [comment]
Wuat? Who the fuck made you a contributor?
inb4 you try to give you more perms

**Comment by ToastyStoemp** [comment]
I have thought about it before
